events{}

http {

    server {
        listen 80;

        Location /auth/ {
            proxy_pass http://auth-service:8000/;
        }

        Location /users/ {
            proxy_pass http://user-service:8000/;
        }

        Location /tasks/ {
            proxy_pass http://task-service:8000/;
        }

        Location / {
            proxy_pass http://frontend:3000/;
        }
    }
}