stages:
  - validate
  - build

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

python_syntax_check:
  stage: validate
  image: python:3.11-slim
  script:
    - python -m compileall services

terraform_validate_dev:
  stage: validate
  image: hashicorp/terraform:1.9
  script:
    - cd terraform/envs/dev
    - terraform init -backend=false
    - terraform validate

yaml_lint:
  stage: validate
  image: python:3.11-slim
  script:
    - pip install --no-cache-dir yamllint
    - yamllint -d "{extends: default, rules: {line-length: {max: 180}}}" k8s ansible .gitlab-ci.yml docker-compose.yml

build_service_images:
  stage: build
  image: docker:27
  services:
    - docker:27-dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  script:
    - docker build -t auth-service:latest services/auth-service
    - docker build -t core-service:latest services/core-service
    - docker build -t api-gateway:latest services/api-gateway
    - docker build -t user-service:latest services/user-service
    - docker build -t task-service:latest services/task-service
    - docker build -t notification-service:latest services/notification-service
    - docker build -t frontend:latest services/frontend
