apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: devops-app
spec:
  type: ClusterIP
  selector:
    app: notification-service
  ports:
    - name: http
      protocol: TCP
      port: 8005
      targetPort: 8000
