apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: devops-app
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
    - name: http
      protocol: TCP
      port: 8006
      targetPort: 8000
