apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-user-service
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: multi-service-devops
  source:
    repoURL: https://github.com/modrikh/multi-service-devops.git
    targetRevision: main
    path: k8s/user-service
  destination:
    server: https://kubernetes.default.svc
    namespace: devops-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
