apiVersion: v1
kind: Service
metadata:
  name: task-service
  namespace: devops-app
spec:
  type: ClusterIP
  selector:
    app: task-service
  ports:
    - name: http
      protocol: TCP
      port: 8004
      targetPort: 8000
